name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Wait for PostgreSQL
        run: |
          for i in $(seq 1 10); do
            nc -z localhost 5432 && echo "PostgreSQL is up and running!" && break
            echo "Waiting for PostgreSQL... ($i/10)"
            sleep 5
          done
          # Fail the job if PostgreSQL is not ready after retries
          nc -z localhost 5432 || (echo "PostgreSQL did not become ready, failing!" && exit 1)

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb

      - name: Run migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb

      - name: Run tests
        run: npm run test
        env:
          DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb
